name: notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.30.0
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_riverpod: ^2.6.1
  go_router: ^17.0.1
  flutter_staggered_grid_view: ^0.7.0
  sqlite3_flutter_libs: ^0.5.24 
  cupertino_icons: ^1.0.8 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  drift_dev: ^2.28.2

flutter:
  uses-material-design: true
